### ISSUE TITLE
local variable 'photoshop' referenced before assignment

### ISSUE THREAD

**Issue by kampelmuehler** [Hvitgar/stylize-datasets#4]
Getting the following traceback

Traceback (most recent call last):
  File "stylize.py", line 150, in <module>
    main()
  File "stylize.py", line 117, in main
    style_img = Image.open(style_path).convert('RGB')
  File "/home/moritz/anaconda3/envs/adain/lib/python3.7/site-packages/PIL/Image.py", line 2690, in open
    im = _open_core(fp, filename, prefix)
  File "/home/moritz/anaconda3/envs/adain/lib/python3.7/site-packages/PIL/Image.py", line 2676, in _open_core
    im = factory(fp, filename)
  File "/home/moritz/anaconda3/envs/adain/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 783, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "/home/moritz/anaconda3/envs/adain/lib/python3.7/site-packages/PIL/ImageFile.py", line 103, in __init__
    self._open()
  File "/home/moritz/anaconda3/envs/adain/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 373, in _open
    handler(self, i)
  File "/home/moritz/anaconda3/envs/adain/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 139, in APP
    self.info["photoshop"] = photoshop
UnboundLocalError: local variable 'photoshop' referenced before assignment

after around 300 images have been processed.

Any thoughts?

**Comment by kampelmuehler** [comment]
Ok, It's a PIL issue, that apparently doesn't occur in 5.4.1. See https://github.com/python-pillow/Pillow/issues/3769.

**Comment by bmitzkus** [comment]
Btw: It will be fixed in the upcoming PIL release
