### ISSUE TITLE
RuntimeError in style_f = vgg(style)

### ISSUE THREAD

**Issue by njustymk** [Hvitgar/stylize-datasets#7]
Traceback (most recent call last):
  File "stylize.py", line 155, in <module>
    main()
  File "stylize.py", line 134, in main
    args.alpha)
  File "stylize.py", line 53, in style_transfer
    style_f = vgg(style)
  File "/root/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/root/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/modules/padding.py", line 163, in forward
    return F.pad(input, self.padding, 'reflect')
  File "/root/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/nn/functional.py", line 2171, in pad
    return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: invalid argument 4: Padding size should be less than the corresponding input dimension, but got: padding (1, 1) at dimension 3 of input [1 x 3 x 1 x 1] at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THCUNN/generic/SpatialReflectionPadding.cu:36

**Comment by njustymk** [comment]
i have solve it , because set a wrong style-size
